# Generated by Django 4.1.7 on 2023-06-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gallery",
                    models.CharField(
                        choices=[
                            ("PIC", "Picture"),
                            ("MPS", "Map"),
                            ("YOP", "Your picture"),
                        ],
                        default="YOP",
                        max_length=3,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/%Y/%m/%d/")),
            ],
        ),
    ]
