# Generated by Django 4.1.7 on 2023-06-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_images_image300_images_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image300",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/%Y/%m/%d/"
            ),
        ),
    ]
