# Generated by Django 4.1.7 on 2023-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_alter_images_image300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image300",
            field=models.ImageField(
                blank=True,
                default="settings.MEDIA_ROOT/pictures/picture.png",
                null=True,
                upload_to="images/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="name",
            field=models.CharField(
                blank=True, default="picture", max_length=200, null=True
            ),
        ),
    ]
