# Generated by Django 4.1.7 on 2023-06-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_alter_images_image300_alter_images_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image300",
            field=models.ImageField(
                blank=True,
                default="settings.MEDIA_ROOT/picture.jpg",
                null=True,
                upload_to="images/%Y/%m/%d/",
            ),
        ),
    ]
