# Generated by Django 4.1.7 on 2023-06-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_images_image300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images1080/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image300',
            field=models.ImageField(blank=True, null=True, upload_to='images300/%Y/%m/%d/'),
        ),
    ]
