# Generated by Django 4.1.7 on 2023-06-26 21:14

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_images_image_alter_images_image300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images1080/%Y/%m/%d/', validators=[gallery.models.custom_validator]),
        ),
    ]
