# Generated by Django 4.1.7 on 2023-06-26 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='images1080/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['gif', 'jpg', 'png', 'bmp', 'jp2'])]),
        ),
    ]
