# Generated by Django 4.1.7 on 2023-06-28 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
