# Generated by Django 4.1.7 on 2023-04-20 21:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="oldCountry",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 4, 20, 21, 55, 45, 181231, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="image",
            name="chapter",
        ),
        migrations.DeleteModel(
            name="OldCountry",
        ),
        migrations.AddField(
            model_name="img",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="img",
                to="index.chapter",
            ),
        ),
        migrations.AddField(
            model_name="img",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="img",
                to="index.image",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="images",
            field=models.ManyToManyField(
                related_name="images", through="index.Img", to="index.image"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="chapter",
            field=models.ManyToManyField(
                related_name="chapter_image", through="index.Img", to="index.chapter"
            ),
        ),
    ]
