# Generated by Django 4.1.7 on 2023-06-14 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0003_img_remove_chapter_oldcountry_comment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="img",
            unique_together={("chapter", "image")},
        ),
    ]
